chore: diff-shared

diff --git a/templates/AddNewPackage/content/.github/workflows/CI.yaml b/templates/AddNewPackage/content/.github/workflows/CI.yaml
--- a/templates/AddNewPackage/content/.github/workflows/CI.yaml
+++ b/templates/AddNewPackage/content/.github/workflows/CI.yaml
@@ -266,16 +266,16 @@ jobs:
         run: |
           {
               if [[ "${{ needs.prerun-ci.result }}" == "failure" || "${{ needs.prerun-ci.result }}" == "cancelled" ]]; then
-                echo "❌  ERROR: Arguments gathering and preparation failed"
-                exit 1
+                  echo "❌  ERROR: Arguments gathering and preparation failed"
+                  exit 1
               fi
               if [[ "${{ needs.run-ci.result }}" == "skipped" ]]; then
-                echo "⚠️  WARNING: CI skipped CI was skipped (push to non-main branch with open PR). Prerelease will not be triggered."
-                echo "              CI skipped (prerun-ci: ${{ needs.prerun-ci.result }}, run-ci: skipped)"
+                  echo "⚠️  WARNING: CI was skipped (push to non-main branch with open PR). Prerelease will not be triggered."
+                  echo "              CI skipped (prerun-ci: ${{ needs.prerun-ci.result }}, run-ci: skipped)"
               elif [[ "${{ needs.run-ci.result }}" == "failure" || "${{ needs.run-ci.result }}" == "cancelled" ]]; then
-                echo "❌  ERROR: CI pipeline ${{ needs.run-ci.result }}"
-                exit 1
+                  echo "❌  ERROR: CI pipeline ${{ needs.run-ci.result }}"
+                  exit 1
               else
-                echo "✅  INFO: CI completed (prerun-ci: ${{ needs.prerun-ci.result }}, run-ci: ${{ needs.run-ci.result }})"
+                  echo "✅  INFO: CI completed (prerun-ci: ${{ needs.prerun-ci.result }}, run-ci: ${{ needs.run-ci.result }})"
               fi
           } >> "$GITHUB_STEP_SUMMARY"
